// PostgreSQL DDL generation from the internal ERD model.

import { foreignKeysOf } from './pgerd.js';

const RESERVED = new Set(
  `all analyse analyze and any array as asc asymmetric authorization binary both case cast
  check collate collation column concurrently constraint create cross current_catalog
  current_date current_role current_schema current_time current_timestamp current_user
  default deferrable desc distinct do else end except false fetch for foreign freeze from
  full grant group having ilike in initially inner intersect into is isnull join lateral
  leading left like limit localtime localtimestamp natural not notnull null offset on only
  or order outer overlaps placing primary references returning right select session_user
  similar some symmetric system_user table tablesample then to trailing true union unique
  user using variadic verbose when where window with`.split(/\s+/)
);

export function quoteIdent(name) {
  const s = String(name ?? '');
  if (/^[a-z_][a-z0-9_$]*$/.test(s) && !RESERVED.has(s)) return s;
  return `"${s.replace(/"/g, '""')}"`;
}

export function quoteLiteral(s) {
  return `'${String(s ?? '').replace(/'/g, "''")}'`;
}

export function qualifiedName(table) {
  return table.schema
    ? `${quoteIdent(table.schema)}.${quoteIdent(table.name)}`
    : quoteIdent(table.name);
}

// "character varying" + 20 -> "character varying(20)"; keeps array suffix last.
export function formatType(col) {
  let type = String(col.type ?? '').trim() || 'text';
  let suffix = '';
  const m = type.match(/^(.*?)((?:\[\])+)$/);
  if (m) {
    type = m[1];
    suffix = m[2];
  }
  const hasLen = col.length !== null && col.length !== undefined && col.length !== '';
  const hasPrec = col.precision !== null && col.precision !== undefined && col.precision !== '';
  if (hasLen && !/\(/.test(type)) {
    const args = hasPrec ? `${col.length},${col.precision}` : `${col.length}`;
    // Time types take precision after the type name but before "with/without time zone".
    const tz = type.match(/^(time|timestamp)( with(?:out)? time zone)$/i);
    type = tz ? `${tz[1]}(${args})${tz[2]}` : `${type}(${args})`;
  }
  return type + suffix;
}

const FK_ACTIONS = { a: 'NO ACTION', r: 'RESTRICT', c: 'CASCADE', n: 'SET NULL', d: 'SET DEFAULT' };

function columnDDL(col) {
  const parts = [quoteIdent(col.name), formatType(col)];
  const raw = col.raw ?? {};
  if (raw.colconstype === 'i' && raw.attidentity) {
    parts.push(`GENERATED ${raw.attidentity === 'a' ? 'ALWAYS' : 'BY DEFAULT'} AS IDENTITY`);
  } else if (raw.colconstype === 'g' && raw.genexpr) {
    parts.push(`GENERATED ALWAYS AS (${raw.genexpr}) STORED`);
  }
  if (col.notNull || col.pk) parts.push('NOT NULL');
  if (col.default !== '' && col.default !== null && col.default !== undefined) {
    parts.push(`DEFAULT ${col.default}`);
  }
  return parts.join(' ');
}

export function generateSQL(model) {
  const out = [];
  const tablesById = new Map(model.tables.map((t) => [t.id, t]));

  out.push('-- Generated by pgsql-erd');
  out.push('BEGIN;');
  out.push('');

  const schemas = [...new Set(model.tables.map((t) => t.schema).filter(Boolean))].filter(
    (s) => s !== 'public'
  );
  for (const s of schemas) out.push(`CREATE SCHEMA IF NOT EXISTS ${quoteIdent(s)};`);
  if (schemas.length) out.push('');

  for (const t of model.tables) {
    const lines = t.columns.map((c) => `    ${columnDDL(c)}`);
    const pk = t.columns.filter((c) => c.pk);
    if (pk.length) {
      const pkName = t.rawData?.primary_key?.[0]?.name;
      const con = pkName ? `CONSTRAINT ${quoteIdent(pkName)} ` : '';
      lines.push(`    ${con}PRIMARY KEY (${pk.map((c) => quoteIdent(c.name)).join(', ')})`);
    }
    const colNames = new Set(t.columns.map((c) => c.name));
    for (const u of t.rawData?.unique_constraint ?? []) {
      const cols = (u.columns ?? []).map((c) => c.column);
      if (!cols.length || !cols.every((c) => colNames.has(c))) continue;
      const con = u.name ? `CONSTRAINT ${quoteIdent(u.name)} ` : '';
      lines.push(`    ${con}UNIQUE (${cols.map(quoteIdent).join(', ')})`);
    }
    out.push(`CREATE TABLE IF NOT EXISTS ${qualifiedName(t)}`);
    out.push('(');
    out.push(lines.join(',\n'));
    out.push(');');
    if (t.description) {
      out.push('');
      out.push(`COMMENT ON TABLE ${qualifiedName(t)}`);
      out.push(`    IS ${quoteLiteral(t.description)};`);
    }
    out.push('');
  }

  for (const t of model.tables) {
    for (const links of foreignKeysOf(model, t)) {
      const ref = tablesById.get(links[0].refTable);
      if (!ref) continue;
      const pairs = links
        .map((l) => [
          t.columns.find((c) => c.attnum === l.localCol),
          ref.columns.find((c) => c.attnum === l.refCol),
        ])
        .filter(([a, b]) => a && b);
      if (!pairs.length) continue;
      const rawFk = links[0].rawFk ?? {};
      const name = links[0].fkName;
      out.push(`ALTER TABLE IF EXISTS ${qualifiedName(t)}`);
      out.push(
        `    ADD${name ? ` CONSTRAINT ${quoteIdent(name)}` : ''} FOREIGN KEY (${pairs
          .map(([a]) => quoteIdent(a.name))
          .join(', ')})`
      );
      out.push(
        `    REFERENCES ${qualifiedName(ref)} (${pairs.map(([, b]) => quoteIdent(b.name)).join(', ')})`
      );
      out.push(`    MATCH ${rawFk.confmatchtype ? 'FULL' : 'SIMPLE'}`);
      out.push(`    ON UPDATE ${FK_ACTIONS[rawFk.confupdtype] ?? 'NO ACTION'}`);
      out.push(`    ON DELETE ${FK_ACTIONS[rawFk.confdeltype] ?? 'NO ACTION'};`);
      out.push('');
    }
  }

  out.push('END;');
  return out.join('\n') + '\n';
}
