// Build the schema context sent to a model. Only what the user selected is
// included; row data is never added here (sample rows are fetched separately
// by the main process, and only when the user allows it).

import { allTables, findTable, neighbourhood, relationshipsOf } from './schema-model.js';

export const DEFAULT_CONTEXT_OPTIONS = {
  selectedTables: true,
  relatedTables: true,
  relationships: true,
  constraints: true,
  entireSchema: false,
  currentScript: true,
  validationErrors: true,
  rowSamples: false,
};

// Table names mentioned in free text (a prompt), qualified or not.
export function tablesInText(schema, text) {
  const s = String(text ?? '');
  const out = [];
  for (const t of allTables(schema)) {
    const esc = (x) => x.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    if (new RegExp(`(^|[^A-Za-z0-9_])(${esc(t.id)}|${esc(t.name)})(?![A-Za-z0-9_])`, 'i').test(s)) out.push(t.id);
  }
  return out;
}

export function describeTable(t, { constraints = true } = {}) {
  const pk = new Set(t.primaryKey?.columns ?? []);
  const fks = new Map();
  for (const fk of t.foreignKeys) fk.columns.forEach((c, i) => fks.set(c, `${fk.refTable}(${fk.refColumns[i]})`));
  const lines = [`TABLE ${t.id}${t.comment ? ` -- ${t.comment}` : ''}`];
  for (const c of t.columns) {
    const parts = [`  ${c.name} ${c.databaseType}`];
    if (!c.nullable) parts.push('NOT NULL');
    if (pk.has(c.name)) parts.push('PK');
    if (c.identity) parts.push(c.identity === 'a' ? 'GENERATED ALWAYS AS IDENTITY' : 'GENERATED BY DEFAULT AS IDENTITY');
    if (c.serial) parts.push('SERIAL');
    if (c.generated) parts.push('GENERATED');
    if (c.defaultValue) parts.push(`DEFAULT ${c.defaultValue}`);
    if (fks.has(c.name)) parts.push(`FK -> ${fks.get(c.name)}`);
    if (c.comment) parts.push(`-- ${c.comment}`);
    lines.push(parts.join(' '));
  }
  if (constraints) {
    for (const u of t.uniques) lines.push(`  UNIQUE (${u.columns.join(', ')})`);
    for (const c of t.checks) lines.push(`  CHECK ${c.expression}${c.name ? ` -- ${c.name}` : ''}`);
    for (const i of t.indexes) lines.push(`  INDEX ${i.name}${i.unique ? ' UNIQUE' : ''} (${i.columns.join(', ')})`);
  }
  return lines.join('\n');
}

// selection: table ids chosen in the diagram or named in the prompt.
// extra: { script: { name, type, source }, validationErrors: [...] }
export function buildContext(schema, selection, options = {}, extra = {}) {
  const o = { ...DEFAULT_CONTEXT_OPTIONS, ...options };
  let ids;
  if (o.entireSchema) ids = allTables(schema).map((t) => t.id);
  else {
    ids = o.selectedTables ? selection.map((s) => findTable(schema, s)?.id).filter(Boolean) : [];
    if (o.relatedTables) ids = neighbourhood(schema, ids);
  }
  ids = [...new Set(ids)];
  const sections = [];
  sections.push(`Database: PostgreSQL. Schema source: ${schema.source ?? 'database'}.`);
  const tables = ids.map((id) => findTable(schema, id)).filter(Boolean);
  if (tables.length) {
    sections.push(tables.map((t) => describeTable(t, { constraints: o.constraints })).join('\n\n'));
  } else {
    const names = allTables(schema).map((t) => t.id);
    sections.push(`Tables in the database (${names.length}): ${names.slice(0, 300).join(', ')}${names.length > 300 ? ', …' : ''}`);
  }
  if (o.relationships && tables.length) {
    const rels = new Set();
    for (const t of tables)
      for (const r of relationshipsOf(schema, t.id))
        rels.add(`${r.from}(${r.columns.join(', ')}) -> ${r.refTable}(${r.refColumns.join(', ')}) ON DELETE ${r.onDelete}`);
    if (rels.size) sections.push(`RELATIONSHIPS\n${[...rels].map((r) => `  ${r}`).join('\n')}`);
  }
  if (schema.enums?.length && tables.length) {
    const used = new Set(tables.flatMap((t) => t.columns.map((c) => c.baseType)));
    const enums = schema.enums.filter((e) => used.has(e.name.toLowerCase()) || used.has(`${e.schema}.${e.name}`.toLowerCase()));
    if (enums.length) sections.push(`ENUMS\n${enums.map((e) => `  ${e.schema}.${e.name}: ${e.values.join(', ')}`).join('\n')}`);
  }
  if (o.currentScript && extra.script?.source) {
    sections.push(`CURRENT SCRIPT (${extra.script.type ?? 'script'}: ${extra.script.name ?? 'untitled'})\n\`\`\`ts\n${extra.script.source}\n\`\`\``);
  }
  if (o.validationErrors && extra.validationErrors?.length) {
    const lines = extra.validationErrors.slice(0, 50).map((e) => `  - ${e.validation ? `[${e.validation}] ` : ''}${e.table ?? ''}${e.row !== undefined ? ` #${e.row}` : ''}: ${e.message}`);
    sections.push(`CURRENT VALIDATION ERRORS\n${lines.join('\n')}`);
  }
  return { text: sections.join('\n\n'), tables: tables.map((t) => t.id) };
}

// System prompt for the assistant, describing the scripting API.
export function assistantSystemPrompt({ tools = false } = {}) {
  return `You are the assistant of pgsql-erd, a PostgreSQL ERD and database scripting workbench.
You help with the schema, SQL and TypeScript scripts that run in the app's script runner.

Scripts are TypeScript with top-level await and these globals (no imports, no Node APIs):
- db.table("schema.table") or db.<schema>.<table>: typed tables with .where({...}).orderBy(col).limit(n).select(...cols), .first(), .count(), .insert(row), .insertMany(rows), .where({...}).update(values), .where({...}).delete().
  where() takes column: value, column: [values] (IN), column: null (IS NULL) or column: { gt, gte, lt, lte, ne, in, notIn, like, ilike, isNull }.
- db.query(sql, params) for raw SQL with $1 placeholders; db.transaction(async tx => ...) for a savepoint; db.describe.table(name), db.describe.relationships(name), db.describe.insertOrder(names).
- validate(name, async () => { ... report.error({ table, row, column, message }) ... }) for validators; report.warning / report.info.
- log(...values) to print output; params holds run parameters.
- faker (person, internet, phone, location, company, lorem, number, datatype, date, string, helpers; faker.seed(n)) for fake data.
- seed.row(table, overrides), seed.fill(table, count, overrides) to generate rows with valid foreign keys; seed.check(table, row).
- ai.structured({ table, prompt }) or ai.structured({ schema, prompt }) returns validated JSON from the model; ai.chat(prompt).
Column values: bigint/numeric are strings, timestamps are Date, json is plain values.

Rules:
- Write complete scripts in a single \`\`\`ts code block. Prefer the typed table API over raw SQL.
- Validators must only read data and report problems with report.error.
- Generators insert data in dependency order (referenced tables first); the user previews them with a dry run.
- Never claim you ran a script: the user reviews and runs scripts themselves.
- Only use tables and columns that exist in the provided schema.${tools ? '\n- Use the tools to look up tables you need instead of guessing.' : ''}`;
}

// Extract fenced code blocks from a reply.
export function codeBlocks(text) {
  const out = [];
  const re = /```([A-Za-z0-9_-]*)[^\n]*\n([\s\S]*?)```/g;
  let m;
  while ((m = re.exec(String(text ?? '')))) out.push({ lang: m[1].toLowerCase(), code: m[2].replace(/\s+$/, '') + '\n' });
  return out;
}
